'use strict';
window.BegemotArchiveUI=(()=>{const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let before=null,busy=false;
 function host(){let d=document.getElementById('archiveDialog');if(!d){d=document.createElement('dialog');d.id='archiveDialog';d.innerHTML='<div class="dialog-header"><h2 id="archiveTitle">Память Бегемота</h2><button id="archiveClose" class="secondary">Закрыть</button></div><div id="archiveBody"></div>';document.body.append(d);d.querySelector('#archiveClose').onclick=()=>d.close();}return d;}
 async function settings(){await BegemotChat.ready;const d=host(),c=BegemotChat.settings;let st={bytes:0,count:0};try{st=await BegemotChat.call({op:'stats'});}catch{}
 document.getElementById('archiveTitle').textContent='Память Бегемота';document.getElementById('archiveBody').innerHTML='<label class="archive-choice"><input id="historyOn" type="checkbox" '+(c.enabled?'checked':'')+'>Сохранять историю на устройстве</label><p>Не более 20 МБ текстовых данных. Старые записи скрываются в архиве, а не удаляются. Если места не хватит, сохранение остановится. Выключение не удаляет накопленное.</p><label class="archive-choice"><input id="contextOn" type="checkbox" '+(c.context?'checked':'')+'>Передавать недавний разговор в ИИ</label><p>До 20 последних сообщений, в пределах размера контекста. Весь архив в ИИ не отправляется.</p><label class="archive-choice"><input id="memoryOn" type="checkbox" '+(c.memory?'checked':'')+'>Использовать мои заметки в разговоре</label><label for="memoryNotes">Что коту стоит помнить</label><textarea id="memoryNotes" rows="6" maxlength="8000" placeholder="Например: люблю короткие ответы, пользуюсь iPhone…">'+esc(BegemotChat.memory)+'</textarea><p>Можно исправить или стереть. Секреты и одноразовые коды сюда не записывайте.</p><button id="saveMemory" class="primary">Сохранить настройки</button> <button id="browseArchive" class="secondary">Открыть архив</button><p>Записей: '+st.count+' · '+(st.bytes/1024/1024).toFixed(2)+' МБ / 20 МБ</p><p id="archiveStatus" role="status"></p><p class="fineprint">Веб: браузер может выделить меньше места и очистить данные. Объём доступного места зависит от Safari. Архив можно удалить в любое время. Удаление приложения или его данных удаляет локальный архив.</p><button id="persistArchive" class="secondary">Запросить сохранение архива в Safari</button>';
 document.getElementById('persistArchive').hidden=!navigator.storage?.persist;if(!d.open)d.showModal();document.getElementById('browseArchive').onclick=()=>archive();document.getElementById('persistArchive').onclick=async()=>{document.getElementById('archiveStatus').textContent=await BegemotChat.persist()?'Постоянное хранилище разрешено.':'Браузер не предоставил гарантию хранения. Не очищайте данные сайта.';};
 document.getElementById('saveMemory').onclick=async()=>{try{await BegemotChat.saveMemory(document.getElementById('memoryNotes').value);BegemotChat.configure({enabled:document.getElementById('historyOn').checked,context:document.getElementById('contextOn').checked,memory:document.getElementById('memoryOn').checked});document.getElementById('archiveStatus').textContent='Сохранено. Старые записи остались на месте.';}catch(e){document.getElementById('archiveStatus').textContent=e.message;}};
 }
 async function archive(){before=null;const d=host();document.getElementById('archiveTitle').textContent='Архив разговоров';document.getElementById('archiveBody').innerHTML='<p>По 40 записей, от новых к старым. Закрытие окна ничего не удаляет.</p><div id="archiveRows"></div><button id="archiveMore" class="secondary">Предыдущие</button><p id="archiveStatus" role="status"></p><details><summary>Удаление архива</summary><p>Это удалит все сохранённые сообщения и проверки с этого устройства. Заметки памяти останутся отдельно.</p><label><input id="confirmArchiveDelete" type="checkbox">Я хочу удалить весь архив</label><button id="archiveDelete" class="secondary">Удалить записи</button></details>';if(!d.open)d.showModal();document.getElementById('archiveMore').onclick=more;document.getElementById('archiveDelete').onclick=async()=>{if(!document.getElementById('confirmArchiveDelete').checked)return;try{await BegemotChat.clear();document.getElementById('archiveRows').replaceChildren();document.getElementById('archiveStatus').textContent='Архив удалён.';}catch(e){document.getElementById('archiveStatus').textContent=e.message;}};await more();}
 async function more(){if(busy)return;busy=true;const b=document.getElementById('archiveMore');b.disabled=true;try{const d=await BegemotChat.call({op:'page',...(before?{before}:{})});for(const x of d.items){const article=document.createElement('article');article.className='archive-entry';article.innerHTML='<small>'+new Date(x.stamp).toLocaleString('ru-RU')+' · '+(x.role==='user'?'Вы':x.role==='check'?'Проверка':'Бегемот')+'</small>'+BegemotRich.html(x.text);document.getElementById('archiveRows').append(article);}before=d.items.at(-1)?.id;b.hidden=d.items.length<40;if(!d.items.length)document.getElementById('archiveStatus').textContent='Больше записей нет.';}catch(e){document.getElementById('archiveStatus').textContent=e.message;}finally{busy=false;b.disabled=false;}}
 window.addEventListener('begemot-storage-error',e=>{let n=document.getElementById('storageWarning');if(!n){n=document.createElement('div');n.id='storageWarning';n.className='storage-warning';n.setAttribute('role','alert');document.body.append(n);}n.textContent=e.detail;});return {settings,archive};})();
