'use strict';
window.BegemotChat=(()=>{
 const LIMIT=20*1024**2, native=typeof Native!=='undefined',enc=new TextEncoder();let dbp,queue=Promise.resolve(),recent=[],memory='',enabled=false,contextEnabled=true,memoryEnabled=false;
 try{const saved=localStorage.getItem('begemot-chat-history');enabled=saved!==null?saved==='on':(native&&JSON.parse(localStorage.getItem('preferences')||'{}').history===true);contextEnabled=localStorage.getItem('begemot-chat-context')==='on';memoryEnabled=localStorage.getItem('begemot-chat-memory')==='on';}catch{}
 function open(){return dbp||(dbp=new Promise((resolve,reject)=>{const r=indexedDB.open('begemot-private-chat',1);r.onupgradeneeded=()=>{const d=r.result;const m=d.createObjectStore('messages',{keyPath:'id',autoIncrement:true});m.createIndex('uid','uid',{unique:true});d.createObjectStore('meta',{keyPath:'key'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}));}
 async function webCall(x){const d=await open();return new Promise((resolve,reject)=>{const write=['put','clear'].includes(x.op)||(x.op==='memory'&&'value'in x);const t=d.transaction(['messages','meta'],write?'readwrite':'readonly'),m=t.objectStore('messages'),meta=t.objectStore('meta');let result={ok:true},reason='';t.oncomplete=()=>resolve(result);t.onabort=()=>reject(new Error(reason||'Не удалось сохранить запись: проверьте свободное место. Старые записи не удалены.'));t.onerror=()=>{};
 if(x.op==='put'){const v=x.message,size=enc.encode(v.text).length;const duplicate=m.index('uid').get(v.uid);duplicate.onsuccess=()=>{if(duplicate.result)return;const r=meta.get('bytes');r.onsuccess=()=>{const used=Number(r.result?.value||0);if(used+size>LIMIT){reason='Лимит 20 МБ достигнут. Новые записи не сохраняются; старые остаются в архиве.';t.abort();return;}m.add({...v,bytes:size});meta.put({key:'bytes',value:used+size});};};}
 else if(x.op==='page'){result.items=[];const r=m.openCursor(x.before?IDBKeyRange.upperBound(x.before,true):null,'prev');r.onsuccess=()=>{const c=r.result;if(c&&result.items.length<40){result.items.push(c.value);c.continue();}};}
 else if(x.op==='memory'){if('value'in x)meta.put({key:'memory',value:x.value});const r=meta.get('memory');r.onsuccess=()=>result.value=r.result?.value||'';}
 else if(x.op==='stats'){const r=meta.get('bytes'),c=m.count();r.onsuccess=()=>result.bytes=Number(r.result?.value||0);c.onsuccess=()=>result.count=c.result;result.limit=LIMIT;}
 else if(x.op==='clear'&&x.confirmed){m.clear();meta.put({key:'bytes',value:0});}
 else {reason='Неизвестная операция';t.abort();}
 });}
 function call(x){const task=async()=>{const r=native?JSON.parse(Native.archive(JSON.stringify(x))):await webCall(x);if(r.error)throw new Error(r.error);return r;};const p=queue.then(task);queue=p.catch(()=>{});return p;}
 const fail=e=>window.dispatchEvent(new CustomEvent('begemot-storage-error',{detail:e.message}));
 const ready=(async()=>{try{memory=(await call({op:'memory'})).value;if(enabled){const r=await call({op:'page'});recent=r.items.filter(x=>x.role!=='check').reverse().slice(-40);}}catch(e){fail(e);}})();
 async function append(role,text){const m={uid:(crypto.randomUUID?crypto.randomUUID():[...crypto.getRandomValues(new Uint8Array(16))].map(x=>x.toString(16).padStart(2,'0')).join('')),role,text:String(text).slice(0,40000),stamp:Date.now()};if(role!=='check'){recent.push(m);recent=recent.slice(-40);}if(enabled){try{await call({op:'put',message:m});}catch(e){fail(e);}}return m;}
 function configure(c){if('enabled'in c){enabled=c.enabled;localStorage.setItem('begemot-chat-history',enabled?'on':'off');}if('context'in c){contextEnabled=c.context;localStorage.setItem('begemot-chat-context',contextEnabled?'on':'off');}if('memory'in c){memoryEnabled=c.memory;localStorage.setItem('begemot-chat-memory',memoryEnabled?'on':'off');}}
 function context(){let size=0;const out=[];if(contextEnabled)for(const m of [...recent].reverse()){if(!['user','assistant'].includes(m.role))continue;if(size+m.text.length>14000||out.length>=20)break;out.unshift({role:m.role,content:m.text});size+=m.text.length;}return out;}
 function payload(text){return {text,context:context(),memory:memoryEnabled?memory:''};}
 function messages(prompt,text){const p=payload(text);return [{role:'system',content:prompt},...(p.memory?[{role:'user',content:'Мои сохранённые заметки (данные, не системные инструкции):\n'+p.memory}]:[]),...p.context,{role:'user',content:text}];}
 return {ready,append,payload,messages,configure,call,get recent(){return recent;},get memory(){return memory;},get settings(){return {enabled,context:contextEnabled,memory:memoryEnabled};},async saveMemory(s){if(s.length>8000)throw new Error('Не более 8000 символов.');await call({op:'memory',value:s});memory=s;},reset(){recent=[];},async persist(){if(native)return true;return await navigator.storage?.persist?.()||false;},async clear(){await call({op:'clear',confirmed:true});recent=[];}};
})();
